"use server";

import { nanoid } from "nanoid";
import { createClient, createAdminClient } from "@/lib/supabase/server";
import { getUser } from "./actions";

interface InviteData {
  email: string;
  role: "manager" | "worker";
  orgId: string;
}

export async function sendInvitation(data: InviteData) {
  const user = await getUser();
  if (!user) {
    return { error: "Not authenticated" };
  }

  const supabase = await createClient();

  // Check if user is owner or manager of the org
  const { data: membership } = await supabase
    .from("org_members")
    .select("role")
    .eq("org_id", data.orgId)
    .eq("user_id", user.id)
    .eq("status", "active")
    .single();

  if (!membership || (membership.role !== "owner" && membership.role !== "manager")) {
    return { error: "You don't have permission to invite members" };
  }

  // Check if email is already a member
  const { data: existingMember } = await supabase
    .from("org_members")
    .select("id, status")
    .eq("org_id", data.orgId)
    .eq("email", data.email.toLowerCase())
    .single();

  if (existingMember) {
    if (existingMember.status === "active") {
      return { error: "This email is already a member of the organization" };
    }
    if (existingMember.status === "invited") {
      return { error: "An invitation has already been sent to this email" };
    }
  }

  // Create org_member record with invited status
  // invitation_token is auto-generated by the database as UUID
  const { data: newMember, error: insertError } = await supabase
    .from("org_members")
    .insert({
      org_id: data.orgId,
      email: data.email.toLowerCase(),
      role: data.role,
      status: "invited",
    })
    .select("invitation_token")
    .single();

  if (insertError) {
    return { error: insertError.message };
  }

  // TODO: Send invitation email with link
  // const inviteUrl = `${process.env.NEXT_PUBLIC_APP_URL}/invite/${newMember.invitation_token}`;

  return {
    success: true,
    message: "Invitation sent successfully",
    inviteToken: newMember?.invitation_token, // Return for testing purposes
  };
}

export async function getInvitation(token: string) {
  const supabase = await createAdminClient();

  const { data: invitation, error } = await supabase
    .from("org_members")
    .select(`
      *,
      organization:organizations(id, name)
    `)
    .eq("invitation_token", token)
    .eq("status", "invited")
    .single();

  if (error || !invitation) {
    return { error: "Invalid or expired invitation" };
  }

  return { invitation };
}

export async function acceptInvitation(token: string) {
  const user = await getUser();
  if (!user) {
    return { error: "Please log in or register first", requiresAuth: true };
  }

  const supabase = await createAdminClient();

  // Get the invitation
  const { data: invitation, error: fetchError } = await supabase
    .from("org_members")
    .select("*")
    .eq("invitation_token", token)
    .eq("status", "invited")
    .single();

  if (fetchError || !invitation) {
    return { error: "Invalid or expired invitation" };
  }

  // Check if email matches
  if (invitation.email.toLowerCase() !== user.email?.toLowerCase()) {
    return { error: "This invitation was sent to a different email address" };
  }

  // Update the invitation to active
  const { error: updateError } = await supabase
    .from("org_members")
    .update({
      user_id: user.id,
      status: "active",
      joined_at: new Date().toISOString(),
      invitation_token: null,
    })
    .eq("id", invitation.id);

  if (updateError) {
    return { error: updateError.message };
  }

  return { success: true, orgId: invitation.org_id };
}

export async function resendInvitation(memberId: string, orgId: string) {
  const user = await getUser();
  if (!user) {
    return { error: "Not authenticated" };
  }

  const supabase = await createClient();

  // Check if user is owner or manager of the org
  const { data: membership } = await supabase
    .from("org_members")
    .select("role")
    .eq("org_id", orgId)
    .eq("user_id", user.id)
    .eq("status", "active")
    .single();

  if (!membership || (membership.role !== "owner" && membership.role !== "manager")) {
    return { error: "You don't have permission to resend invitations" };
  }

  // Get the member
  const { data: member } = await supabase
    .from("org_members")
    .select("*")
    .eq("id", memberId)
    .eq("org_id", orgId)
    .eq("status", "invited")
    .single();

  if (!member) {
    return { error: "Invitation not found" };
  }

  // Generate new token
  const newToken = nanoid(32);

  const { error: updateError } = await supabase
    .from("org_members")
    .update({
      invitation_token: newToken,
      invited_at: new Date().toISOString(),
    })
    .eq("id", memberId);

  if (updateError) {
    return { error: updateError.message };
  }

  // TODO: Send invitation email

  return { success: true, message: "Invitation resent" };
}
